# .readthedocs.yaml
version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"

python:
  install:
    - requirements: docs/requirements.txt  # Adjust this if your requirements.txt is elsewhere
    - path: .

sphinx:
  configuration: docs/source/conf.py

